spring:
    datasource:
      url: jdbc:postgresql://localhost:5430/postgres_db
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
    liquibase:
      enabled: true
      contexts: test_data